version: '3'
services:
  ll-string-patterns:
    build: .
    container_name: ll-string-patterns-service
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_NAME=string_patterns
      - DB_USER=postgres
      - DB_PASS=postgres
  db:
    image: 'postgres:15-alpine'
    container_name: ll-string-patterns-service-db
    ports:
      - "5432:5432"
    volumes:
      - ll-string-patterns-service-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=string_patterns
      - POSTGRES_PORT=5432
  flyway:
    container_name: flyway
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
      - FLYWAY_URL=jdbc:postgresql://db:5432/string_patterns
    image: flyway/flyway:latest
    command: -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - db

volumes:
  ll-string-patterns-service-db:
    external: false
