spring:
  main:
    banner-mode: OFF
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_HOST:localhost}/${DB_NAME:string_patterns}"
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    hikari:
      minimumIdle: 1
      maximumPoolSize: 5
      connectionTimeout: 15000
      validationTimeout: 1000
  flyway:
    enabled: false
